//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalculatorWebApplication.CalculatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorService.calculatorwebserviceSoap")]
    public interface calculatorwebserviceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        int Add(int firstnumber, int secontnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<int> AddAsync(int firstnumber, int secontnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        int Sub(int firstnumber, int secontnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sub", ReplyAction="*")]
        System.Threading.Tasks.Task<int> SubAsync(int firstnumber, int secontnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        int Mul(int firstnumber, int secontnumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Mul", ReplyAction="*")]
        System.Threading.Tasks.Task<int> MulAsync(int firstnumber, int secontnumber);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface calculatorwebserviceSoapChannel : CalculatorWebApplication.CalculatorService.calculatorwebserviceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class calculatorwebserviceSoapClient : System.ServiceModel.ClientBase<CalculatorWebApplication.CalculatorService.calculatorwebserviceSoap>, CalculatorWebApplication.CalculatorService.calculatorwebserviceSoap {
        
        public calculatorwebserviceSoapClient() {
        }
        
        public calculatorwebserviceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public calculatorwebserviceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculatorwebserviceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public calculatorwebserviceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int Add(int firstnumber, int secontnumber) {
            return base.Channel.Add(firstnumber, secontnumber);
        }
        
        public System.Threading.Tasks.Task<int> AddAsync(int firstnumber, int secontnumber) {
            return base.Channel.AddAsync(firstnumber, secontnumber);
        }
        
        public int Sub(int firstnumber, int secontnumber) {
            return base.Channel.Sub(firstnumber, secontnumber);
        }
        
        public System.Threading.Tasks.Task<int> SubAsync(int firstnumber, int secontnumber) {
            return base.Channel.SubAsync(firstnumber, secontnumber);
        }
        
        public int Mul(int firstnumber, int secontnumber) {
            return base.Channel.Mul(firstnumber, secontnumber);
        }
        
        public System.Threading.Tasks.Task<int> MulAsync(int firstnumber, int secontnumber) {
            return base.Channel.MulAsync(firstnumber, secontnumber);
        }
    }
}
